### ISSUE TITLE
TextNode, CardMaker and legacy egg rendering issues

### ISSUE THREAD

**Issue by Fak3** [Moguri/panda3d-simplepbr#15]
I created a simple scene with [box.egg](https://github.com/panda3d/panda3d/blob/master/models/box.egg), few TextNodes, and CardMaker:
```python
        self.model = loader.loadModel("models/box")
        self.model.reparentTo(self.render)
        self.model.set_pos(0, 2, 0)
        self.model.set_hpr(45, 0, 0.)
        
        cm = CardMaker("mycard")
        cm.setColor(255,0,0,0)
        cm.setFrame(-10, 10, -10, 10)
        self.render.attachNewNode(cm.generate()).lookAt(0, 0, -1)
        
        def txtnode(txt, pos):
            text = TextNode(txt)
            text.setText(txt)
            textNodePath = self.render.attachNewNode(text)
            textNodePath.setPos(*pos)
        txtnode('0', pos=(0,0,0))
        txtnode('X', pos=(1,0,0))
        txtnode('Y', pos=(0,1,0))
```

I noticed the TextNode does not render at all, CardMaker have wrong color, and box is missing texture (is it because of #6 ?)

Is there any quirk to make those three render close to the classic panda renderer? Or is there any replacement for TextNode and CardMaker i can use?

Classic panda pipeline:
![b1-classic](https://user-images.githubusercontent.com/991641/86531572-26fd6280-becb-11ea-96cd-6780bce8171e.jpeg)
simplepbr:
![b1-pbr](https://user-images.githubusercontent.com/991641/86531578-2f559d80-becb-11ea-82df-04e1b842fb7c.jpeg)

**Comment by Moguri** [comment]
The simplepbr shader does not have anything for text rendering, so you'll want to use the auto-shader for text nodes:
```python
        def txtnode(txt, pos):
            text = TextNode(txt)
            text.setText(txt)
            textNodePath = self.render.attachNewNode(text)
            textNodePath.setPos(*pos)
            textNodePath.setShaderAuto(True)
```

The CardMaker and box issues are less straight-forward. For the CardMaker, I suspect a missing texture could be causing problems. For a missing texture, I think Panda will generate an all black texture, which could be overriding the color set by CardMaker. I am not sure if this color value is an object color (e.g., passed to the shader as a uniform) or a vertex color, but in either case, I believe the color would get multiplied by the black color from the generated texture, which would result in black.

For the cube, I am less certain about what is going on. #6 is more about colors being too dark or too light, but your texture does not appear to be rendering at all.

**Comment by Moguri** [comment]
Things should be working now. If not, please let me know so we can either re-open this issue or file some new, more specific issues.
