### ISSUE TITLE
Getting black (models/shaders) when using autoshader

### ISSUE THREAD

**Issue by Oneil974** [Moguri/panda3d-simplepbr#17]
Hi,

First, really thank for your gltf support, simplepbr, CLI converter etc... It's really more easy to integrate blender models.

So I'm getting an issue when I activate `render.setShaderAuto()` to get shadows, all textures, shaders etc are getting black.

Could you help me about this?

![image](https://user-images.githubusercontent.com/11059074/92085479-f017d000-edd9-11ea-9557-2a425b065099.png)
![image](https://user-images.githubusercontent.com/11059074/92085533-032aa000-edda-11ea-9c86-daa5edcd646c.png)

**Comment by rdb** [comment]
panda3d-simplepbr is not compatible with setShaderAuto.  If you use setShaderAuto, the simplepbr shaders become disabled.

You should rather use the built-in shadow support of panda3d-simplepbr, which can be enabled by passing `enable_shadows=True` in the `init()` call.

**Comment by Oneil974** [comment]
Ok, tested too but don't seem to work or maybe I forget something.
I will try again.
Otherwise,
Looks like https://github.com/kergalym/YABEE was updated (today) so I can now use egg format and I think I need no more simplepbr for the moment.

Thanks again
