### ISSUE TITLE
Ambient Lights don't  affect the scene

### ISSUE THREAD

**Issue by thetestgame** [Moguri/panda3d-simplepbr#19]
While attempting to shade a scene for a new project I discovered ambient lights don't work with simplepbr. Direcitonal and point lights work but ambient don't seem to effect the scene. Simplepbr has worked perfectly for me in the past so this is likely a newer issue.

https://gyazo.com/12c27431517617797628b6ccc8671845

I've included an example python script that encounters this issue.
```python
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase
import simplepbr

class AppBase(ShowBase):

    def __init__(self):
        super().__init__()
        self.pipeline = simplepbr.init()

        panda = loader.load_model('panda')
        panda.reparent_to(self.render)

        self.ambient = render.attach_new_node(AmbientLight('ambient'))
        self.ambient.node().set_color((.8, .8, .8, 1))
        render.set_light(self.ambient)

if __name__ == '__main__':
    base = AppBase()
    base.run()
```

**Comment by rdb** [comment]
The test case in question shows up black because there's no material with base color assigned.  Nothing to do with the ambient light.

**Comment by rdb** [comment]
@thetestgame shared a model with me that was black under an ambient light for a different reason: the material was marked as metallic.

Apparently, a model with metallic=1 does not respond to ambient lights in simplepbr.

It's a little unclear to me how an ambient light *should* behave for a metal, given that ambient lights don't really make any sense for PBR to begin with.  I suppose an ambient light is a bit like light coming from all directions hitting the object equally, in which case that I would think it should also affect the specular as much as the diffuse.

**Comment by serkkz** [comment]
Getting acquainted with the PBR samples, I noticed that there is a metal map, I think this 'metallic=1' flag should simply activate it.
