### ISSUE TITLE
Unclear how (or if even possible) to specify package_data_dirs in setup.cfg

### ISSUE THREAD

**Issue by Clockwork-Muse** [Moguri/panda3d-simplepbr#24]
I'm attempting to use a setup.cfg instead of a setup.py (because setuptools is transitioning to setup.cfg), but directions on how to specify the shader inclusion this way aren't shown, and my attempts so far have been unsuccessful (possibly due to how panda3d reads the file).

**Comment by Moguri** [comment]
Since shaders are now bundled into a shaders.py module, specifying `package_data_dirs` is no longer necessary.
