### ISSUE TITLE
OSX: shaders loaded from nonstandard location

### ISSUE THREAD

**Issue by kukulski** [Moguri/panda3d-simplepbr#29]
tldr:  on OSX, _load_shader_str should look in .app/Contents/Resources/shaders instead of .app/Contents/MacOS/shaders
(or we need a sample setup.py / setup.cfg that copies the shaders to Contents/MacOS/shaders)  

presently I'm using   `'package_data_dirs': {'simplepbr': [('simplepbr/shaders*', '', {})]},` in my setup.py, and manually editing the generated app to put the shaders where simplepbr looks for them
    
seems like an easy enough fix -- let me see if I can figure out the workflow for a local fix + pull-request

**Comment by kukulski** [comment]
https://github.com/Moguri/panda3d-simplepbr/pull/30

**Comment by Moguri** [comment]
Fixed by b9129337fbdc37939f09ae4c0af2c662d9bf97ad
