### ISSUE TITLE
Hardware skinning leads to incorrect lighting

### ISSUE THREAD

**Issue by Epihaius** [Moguri/panda3d-simplepbr#33]
Hi,

When I enable hardware skinning, I find that the shading on an animated model looks wrong -- at least when it is not in the default pose.

When I set the pose of the model such that a part rotates reasonably far away from its starting orientation, the incorrect lighting becomes very noticeable.
In general, it looks like the light is "baked into" the model, disregarding any deformations caused by the animation.

Here is a screenshot that shows this quite clearly:

![pbr_hardware_skinning001](https://user-images.githubusercontent.com/16452534/143689726-c99f145c-b080-474c-b6f7-9ed5e9ba2a21.png)

To the left is a model that is affected by the hardware skinning, while the model to the right has a ShaderAttrib set that explicitly turns off hardware skinning, such that its vertices are animated on the CPU.

It seems that to fix this, all that is needed is to transform the vertex normal with the skinning matrix, as is done with the vertex position.
(Intuitively, it occurred to me that the same might have to be done with the tangent vector as well, but that does not seem to lead to exactly the same shading as obtained with CPU-skinning.)

So the code for `simplepbr.vert` might be changed to the following:

```c++
#version 120

#ifndef MAX_LIGHTS
    #define MAX_LIGHTS 8
#endif

#ifdef ENABLE_SHADOWS
uniform struct p3d_LightSourceParameters {
    vec4 position;
    vec4 diffuse;
    vec4 specular;
    vec3 attenuation;
    vec3 spotDirection;
    float spotCosCutoff;
    sampler2DShadow shadowMap;
    mat4 shadowViewMatrix;
} p3d_LightSource[MAX_LIGHTS];
#endif

#ifdef ENABLE_SKINNING
uniform mat4 p3d_TransformTable[100];
#endif

uniform mat4 p3d_ProjectionMatrix;
uniform mat4 p3d_ModelViewMatrix;
uniform mat3 p3d_NormalMatrix;
uniform mat4 p3d_TextureMatrix;

attribute vec4 p3d_Vertex;
attribute vec4 p3d_Color;
attribute vec3 p3d_Normal;
attribute vec4 p3d_Tangent;
attribute vec2 p3d_MultiTexCoord0;
#ifdef ENABLE_SKINNING
attribute vec4 transform_weight;
attribute uvec4 transform_index;
#endif


varying vec3 v_position;
varying vec4 v_color;
varying mat3 v_tbn;
varying vec2 v_texcoord;
#ifdef ENABLE_SHADOWS
varying vec4 v_shadow_pos[MAX_LIGHTS];
#endif

void main() {
#ifdef ENABLE_SKINNING
    mat4 skin_matrix = (
        p3d_TransformTable[transform_index.x] * transform_weight.x +
        p3d_TransformTable[transform_index.y] * transform_weight.y +
        p3d_TransformTable[transform_index.z] * transform_weight.z +
        p3d_TransformTable[transform_index.w] * transform_weight.w
    );
    vec4 vert_pos4 = p3d_ModelViewMatrix * skin_matrix * p3d_Vertex;
    vec3 normal = normalize(p3d_NormalMatrix * (skin_matrix * vec4(p3d_Normal.xyz, 0.0)).xyz);
#else
    vec4 vert_pos4 = p3d_ModelViewMatrix * p3d_Vertex;
    vec3 normal = normalize(p3d_NormalMatrix * p3d_Normal);
#endif
    v_position = vec3(vert_pos4);
    v_color = p3d_Color;
    v_texcoord = (p3d_TextureMatrix * vec4(p3d_MultiTexCoord0, 0, 1)).xy;
#ifdef ENABLE_SHADOWS
    for (int i = 0; i < p3d_LightSource.length(); ++i) {
        v_shadow_pos[i] = p3d_LightSource[i].shadowViewMatrix * vert_pos4;
    }
#endif

    vec3 tangent = normalize(vec3(p3d_ModelViewMatrix * vec4(p3d_Tangent.xyz, 0.0)));
    vec3 bitangent = cross(normal, tangent) * p3d_Tangent.w;
    v_tbn = mat3(
        tangent,
        bitangent,
        normal
    );

    gl_Position = p3d_ProjectionMatrix * vert_pos4;
}
```

This is what the proposed change leads to:

![pbr_hardware_skinning002](https://user-images.githubusercontent.com/16452534/143689755-25f755f7-7a84-498b-b74f-c7cd6614a73b.png)

Both models now look pretty much identical, I think! :)

If you want this as a PR, let me know.

In case you want to test this more in-depth (animation might be more revealing than mere screenshots), the following code sample might help (the required assets are attached below the code):

```python
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase
from direct.actor.Actor import Actor
import simplepbr


class App(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)

        simplepbr.init(use_normal_maps=True, use_hardware_skinning=True, use_330=True)

        # set up a light source
        p_light = PointLight("point_light")
        p_light.set_color((1., 1., 1., 1.))
        self.light = self.camera.attach_new_node(p_light)
        self.light.set_pos(5., -100., 7.)
        self.render.set_light(self.light)

        self.trackball.node().set_y(10.)

        # Create a hardware-skinned actor using simplepbr.
        self.actor = Actor("model.gltf")
        self.actor.reparent_to(self.render)
        self.actor.set_h(180.)
        self.actor.set_x(-1.5)
#        self.actor.loop("walk")
        self.actor.pose("walk", 20)

        # Create a CPU-transformed actor, for reference.
        self.actor2 = Actor("model.gltf")
        self.actor2.reparent_to(self.render)
        self.actor2.set_h(180.)
        attrib = base.render.get_state().get_attrib(ShaderAttrib)
        # explicitly tell Panda to transform the vertices on the CPU
        attrib = attrib.set_flag(ShaderAttrib.F_hardware_skinning, False)
        self.actor2.set_attrib(attrib)
        self.actor2.set_x(1.5)
#        self.actor2.loop("walk")
        self.actor2.pose("walk", 20)


app = App()
app.run()
```

[model.zip](https://github.com/Moguri/panda3d-simplepbr/files/7612072/model.zip)

The .blend file is included in the above .zip file a well, should you need it.

**Comment by rdb** [comment]
I agree.

Technically, the normals should be transformed by the inverse transpose of the product of the model and skinning matrices. Otherwise the normals won't be transformed properly in the presence of non-uniform scales.

However, that would be more expensive to calculate, and the suggested fix is still better than not transforming the normal at all—it will only not produce correct results if the joint is scaled by a non-uniform scale.

**Comment by Epihaius** [comment]
One more reason not to scale non-uniformly. :)

**Comment by Moguri** [comment]
Yes, the normals need to be transformed too, and I'm a bit surprised that I missed this. Please feel free to open up a PR. I am okay with skipping non-uniform scale for now, but it can be useful for squash and stretch animations.

**Comment by Epihaius** [comment]
> I am okay with skipping non-uniform scale for now, but it can be useful for squash and stretch animations.

Would it be worthwhile to add an option to `simplepbr.init` that allows the user to switch to the more complex calculation mentioned by rdb when they need to play such animations?
