### ISSUE TITLE
Implement image-based lighting

### ISSUE THREAD

**Issue by rdb** [Moguri/panda3d-simplepbr#36]
Presently, shiny metals will show up pitch black in simplepbr, because of the absence of environmental reflection, as well as the fact that the size of the specular highlight approaches zero when the roughness approaches 1.

To properly support metals, and give a more aesthetically pleasing result overall, it is necessary to implement image-based lighting.  To keep things simple, the split-sum approximation could be used (as described in the [Unreal paper](https://cdn2.unrealengine.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf)), which produces good results except at grazing angles.

I think this will require the ability to provide an environment map and implementing the necessary pre-filtering to create the split-sum approximation maps, either with a separate tool or at runtime.  Any changes to Panda that may be helpful for this (eg. putting the filter algorithm in PNMImage) should be considered so that they can be implemented by 1.11.

**Comment by cybereality** [comment]
I'm working on my own engine, and I'm having some issues with performance on mobile. You can see the Vulkan version on desktop here, which looks pretty nice (based on the PBR tutorial on LearnOpenGL).

https://www.youtube.com/watch?v=GaRc7ziealk

Currently I'm porting this to OpenGL/WebGL and performance is barely 30 FPS at 1080p. I'd like to see if I can help add image based lighting to SimplePBR. The shader right now looks pretty optimized, but doesn't appear great without the environment mapping. I'm not too familiar with Panda3D, but I'll start seeing if I can get something working. Are you open to pull requests?

**Comment by Moguri** [comment]
An IBL implementation is being worked on in the `ibl` branch. I am always open to pull requests, but it would be helpful if you hopped on the Panda3D Discord channel so we could discuss potential changes before you got to work.

The `ibl` branch currently has the shaders implemented for IBL diffuse (using spherical harmonics) and IBL specular (using the split-sum approximation). Calculating the spherical harmonic coefficients and pre-filtering the environment maps are done on the CPU in Python, which makes it pretty slow.

What is still needed:
* Compute shader fast-path for calculating spherical harmonics coefficients
* Compute shader fast-path for pre-filtering the environment map
* Compute shader fast-path for generating the BRDF LUT (lower priority)
* Allow reading/writing `env` files (BAM-serialized `EnvMap`) (in progress)
* Script for offline creation of `env` files (sort of in progress)
* Caching prepared EnvMap data (in progress)

**Comment by cybereality** [comment]
Okay, cool. Let me get up to speed on Panda3D first, as I haven't used it in like 10 years. But all that stuff sounds doable.
