### ISSUE TITLE
Issue with TextNode color

### ISSUE THREAD

**Issue by Linkshanderin** [Moguri/panda3d-simplepbr#44]
I have a very simple, default-options example scene with one text node that is intended to be red:
```
text = "Example Text"
textNode = TextNode(text)
textNode.setText(text)
textNode.setTextColor((1, 0, 0, 1))
textNodePath = self.render.attachNewNode(textNode)
textNodePath.setPos(0, 10, 0)
textNodePath.setScale(2)
```
This text node, however, is *white*. Going back to a normal, "shaderless" Panda scene makes the color red.. I saw [this fix](https://github.com/Moguri/panda3d-simplepbr/commit/430f06336975e683ecedd046235dd7e7ed7039a0) was made a few months ago in response to an [issue on the main Panda3D repo](https://github.com/panda3d/panda3d/issues/1280).

Is there something else that I'm suppose  to apply to my text node, nodepath, or something else?

**Comment by serkkz** [comment]
It might work.

`textNodePath.setColor((1, 0, 0, 1))`
