### ISSUE TITLE
Use multiple Camera nodes with the PBR shaders (actually just for Tone Mapping)

### ISSUE THREAD

**Issue by nb-programmer** [Moguri/panda3d-simplepbr#47]
I have a scene with two cameras (one is the viewport, another is just a render-to-buffer that I need for a different reason).

The issue is: when creating the Pipeline, the `camera_node` parameter is used for the input in creating a FilterManager to perform Tone Mapping (if I understood this correctly). But since I have two cameras, the Tone Mapping isn't applied to that one, so the image is dim (see Screenshot with BufferViewer active).

 One solution might be to add a method of attaching the Tone Mapping shader to arbitrary Cameras using a new method, or add an option to disable Tone Mapping and use SDR directly (if that is possible). #46 is suggesting similarly, but it isn't related to this issue. This issue applies just for multiple Cameras since the rendered texture will be very dim compared to the viewport.

Screenshot with Buffer Viewer. Left-most is the 2nd camera (POV of the player), right-most seems to be the `scene_tex` texture used for tone mapping.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/46126206/218327733-7d371c94-523e-480c-865c-e969d6bea208.png">

**Comment by rdb** [comment]
I think you just need to use simplepbr.init twice, right?  One for each camera.

**Comment by nb-programmer** [comment]
@rdb Yes I guess that can be done, but I don't know the performance implication of creating two pipelines vs just attaching a filter for tone mapping to the camera.

**Comment by rdb** [comment]
You can't just "attach a filter for tone mapping to the camera" without setting up a pipeline.  This is because to be able to filter, you need to render the scene to a texture.  So I think there is no other way to accomplish what you want than by creating a second pipeline.

**Comment by Moguri** [comment]
There is not much overhead in running multiple `Pipeline` instances, and I agree that it is the way to go for doing this. Also, see [this forum thread](https://discourse.panda3d.org/t/how-to-use-multiple-cameras-with-simplepbr/29187/12) for more information on doing this as well as an example snippet.
