### ISSUE TITLE
Clear color not working correctly, alpha value not respected

### ISSUE THREAD

**Issue by NFSS10** [Moguri/panda3d-simplepbr#60]
Setting the alpha value to `0` or any other value doesn't change the alpha channel value. Because of this I'm not able to get screenshots with transparency.

```python
self.win.setClearColor((0, 0, 0, 0))
```
I think it's because of this: https://github.com/Moguri/panda3d-simplepbr/blob/694f9a08365f61c9bc4ae28d5664f0502e053df7/simplepbr/shaders/tonemap.frag#L35

Is there something that I'm missing?

**Comment by Moguri** [comment]
Fixed by manually merging #61
